using ClashRoyaleClanWarsAPI.Domain.Enum;
using ClashRoyaleClanWarsAPI.Domain.Models.Card.Implementation;

namespace ClashRoyaleClanWarsAPI.Infrastructure.Persistance.Seed;

public static class CardsSeed
{
    public static List<TroopModel> TroopsCards { get; } = new List<TroopModel>
    {
        new TroopModel()
        {   Name="Knight",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=3,
            HitPoints=690,
            Damage=79,
            AreaDamage=false,
            Amount=1,
            InitialLevel=1,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=1.2f,
            HitSpeed=1.2f,
            Transport = TransportCardEnum.Ground,
            Description="A tough melee fighter. The Barbarian's handsome, cultured cousin. Rumor has it that he was knighted based on the sheer awesomeness of his mustache alone.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/jAj1Q5rclXxU9kVImGqSJxa4wEMfEhvwNQ_4jiGUuqg.png",
        },
        new TroopModel()
        {   Name="Archers",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=3,
            HitPoints=119,
            Damage=42,
            AreaDamage=false,
            Amount=2,
            InitialLevel=1,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=5,
            HitSpeed=0.9f,
            Transport = TransportCardEnum.Ground,
            Description="A pair of lightly armored ranged attackers. They'll help you take down ground and air units, but you're on your own with hair coloring advice.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/W4Hmp8MTSdXANN8KdblbtHwtsbt0o749BbxNqmJYfA8.png",
        },
        new TroopModel()
        {   Name="Goblins",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=2,
            HitPoints=79,
            Damage=47,
            AreaDamage=false,
            Amount=4,
            InitialLevel=1,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Very_Fast,
            Range=0.5f,
            HitSpeed=1.1f,
            Transport = TransportCardEnum.Ground,
            Description="Four fast, unarmored melee attackers. Small, fast, green and mean!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/X_DQUye_OaS3QN6VC9CPw05Fit7wvSm3XegXIXKP--0.png",
        },
        new TroopModel()
        {   Name="Giant",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=5,
            HitPoints=1930,
            Damage=120,
            AreaDamage=false,
            Amount=1,
            InitialLevel=3,
            Target=TargetCardEnum.Buildings,
            Speed= SpeedCardEnum.Slow,
            Range=1.2f,
            HitSpeed=1.5f,
            Transport = TransportCardEnum.Ground,
            Description="Slow but durable, only attacks buildings. A real one-man wrecking crew!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/Axr4ox5_b7edmLsoHxBX3vmgijAIibuF6RImTbqLlXE.png",
        },
        new TroopModel()
        {   Name="P.E.K.K.A",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=7,
            HitPoints=2350,
            Damage=510,
            AreaDamage=false,
            Amount=1,
            InitialLevel=6,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Slow,
            Range=1.2f,
            HitSpeed=1.8f,
            Transport = TransportCardEnum.Ground,
            Description="A heavily armored, slow melee fighter. Swings from the hip, but packs a huge punch.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/MlArURKhn_zWAZY-Xj1qIRKLVKquarG25BXDjUQajNs.png",
        },
        new TroopModel()
        {   Name="Minions",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=3,
            HitPoints=90,
            Damage=46,
            AreaDamage=false,
            Amount=3,
            InitialLevel=1,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Fast,
            Range=1.6f,
            HitSpeed=1,
            Transport = TransportCardEnum.Air,
            Description="Three fast, unarmored flying attackers. Roses are red, minions are blue, they can fly, and will crush you!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/yHGpoEnmUWPGV_hBbhn-Kk-Bs838OjGzWzJJlQpQKQA.png",
        },
        new TroopModel()
        {   Name="Ballon",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=5,
            HitPoints=1050,
            Damage=400,
            AreaDamage=false,
            Amount=1,
            InitialLevel=6,
            Target=TargetCardEnum.Buildings,
            Speed= SpeedCardEnum.Medium,
            Range=0.1f,
            HitSpeed=2,
            Transport = TransportCardEnum.Air,
            Description="As pretty as they are, you won't want a parade of THESE balloons showing up on the horizon. Drops powerful bombs and when shot down, crashes dealing area damage.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/qBipxLo-3hhCnPrApp2Nn3b2NgrSrvwzWytvREev0CY.png",
        },
        new TroopModel()
        {   Name="Witch",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=5,
            HitPoints=524,
            Damage=84,
            AreaDamage=true,
            Amount=1,
            InitialLevel=6,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=5.5f,
            HitSpeed=1.1f,
            Transport = TransportCardEnum.Ground,
            Description="Summons Skeletons, shoots destructo beams, has glowing pink eyes that unfortunately don't shoot lasers.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/cfwk1vzehVyHC-uloEIH6NOI0hOdofCutR5PyhIgO6w.png",
        },
        new TroopModel()
        {   Name="Barbarians",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=5,
            HitPoints=262,
            Damage=75,
            AreaDamage=false,
            Amount=5,
            InitialLevel=1,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=0.7f,
            HitSpeed=1.3f,
            Transport = TransportCardEnum.Ground,
            Description="A horde of melee attackers with mean mustaches and even meaner tempers",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/TvJsuu2S4yhyk1jVYUAQwdKOnW4U77KuWWOTPOWnwfI.png",
        },
        new TroopModel()
        {   Name="Golem",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=8,
            HitPoints=3200,
            Damage=195,
            AreaDamage=false,
            Amount=1,
            InitialLevel=6,
            Target=TargetCardEnum.Buildings,
            Speed= SpeedCardEnum.Slow,
            Range=0.75f,
            HitSpeed=2.5f,
            Transport = TransportCardEnum.Ground,
            Description="Slow but durable, only attacks buildings. When destroyed, explosively splits into two Golemites and deals area damage!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/npdmCnET7jmVjJvjJQkFnNSNnDxYHDBigbvIAloFMds.png",
        },
        new TroopModel()
        {   Name="Skeletons",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=1,
            HitPoints=32,
            Damage=32,
            AreaDamage=false,
            Amount=3,
            InitialLevel=1,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Fast,
            Range=0.5f,
            HitSpeed=1,
            Transport = TransportCardEnum.Ground,
            Description="Three fast, very weak melee fighters. Surround your enemies with this pile of bones!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/oO7iKMU5m0cdxhYPZA3nWQiAUh2yoGgdThLWB1rVSec.png",
        },
        new TroopModel()
        {   Name="Valkyrie",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=4,
            HitPoints=900,
            Damage=126,
            AreaDamage=true,
            Amount=1,
            InitialLevel=3,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=1.2f,
            HitSpeed=1.5f,
            Transport = TransportCardEnum.Ground,
            Description="Tough melee fighter, deals area damage around her. Swarm or horde, no problem! She can take them all out with a few spins.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/0lIoYf3Y_plFTzo95zZL93JVxpfb3MMgFDDhgSDGU9A.png",
        },
        new TroopModel()
        {   Name="Skeleton Army",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=3,
            HitPoints=51,
            Damage=51,
            AreaDamage=false,
            Amount=15,
            InitialLevel=6,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Fast,
            Range=0.5f,
            HitSpeed=1,
            Transport = TransportCardEnum.Ground,
            Description="Spawns an army of Skeletons. Meet Larry and his friends Harry, Terry, Gerry, Mary, etc.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/fAOToOi1pRy7svN2xQS6mDkhQw2pj9m_17FauaNqyl4.png",
        },
        new TroopModel()
        {   Name="Bomber",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=2,
            HitPoints=130,
            Damage=87,
            AreaDamage=true,
            Amount=1,
            InitialLevel=1,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=4.5f,
            HitSpeed=1.8f,
            Transport = TransportCardEnum.Ground,
            Description="Small, lightly protected skeleton who throws bombs. Deals area damage that can wipe out a swarm of enemies.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/12n1CesxKIcqVYntjxcF36EFA-ONw7Z-DoL0_rQrbdo.png",
        },
        new TroopModel()
        {   Name="Musketeer",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=4,
            HitPoints=340,
            Damage=103,
            AreaDamage=false,
            Amount=1,
            InitialLevel=3,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=6,
            HitSpeed=1,
            Transport = TransportCardEnum.Ground,
            Description="Don't be fooled by her delicately coiffed hair, the Musketeer is a mean shot with her trusty boomstick.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/Tex1C48UTq9FKtAX-3tzG0FJmc9jzncUZG3bb5Vf-Ds.png",
        },
        new TroopModel()
        {   Name="Baby Dragon",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=4,
            HitPoints=720,
            Damage=100,
            AreaDamage=true,
            Amount=1,
            InitialLevel=6,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Fast,
            Range=3.5f,
            HitSpeed=1.5f,
            Transport = TransportCardEnum.Air,
            Description="Burps fireballs from the sky that deal area damage. Baby dragons hatch cute, hungry and ready for a barbeque.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/cjC9n4AvEZJ3urkVh-rwBkJ-aRSsydIMqSAV48hAih0.png",
        },
        new TroopModel()
        {   Name="Prince",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=5,
            HitPoints=1200,
            Damage=245,
            AreaDamage=false,
            Amount=1,
            InitialLevel=6,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=1.6f,
            HitSpeed=1.4f,
            Transport = TransportCardEnum.Ground,
            Description="Don't let the little pony fool you. Once the Prince gets a running start, you WILL be trampled. Deals double damage once he gets charging.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/3JntJV62aY0G1Qh6LIs-ek-0ayeYFY3VItpG7cb9I60.png",
        },
        new TroopModel()
        {   Name="Wizard",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=4,
            HitPoints=340,
            Damage=133,
            AreaDamage=true,
            Amount=1,
            InitialLevel=3,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=5.5f,
            HitSpeed=1.4f,
            Transport = TransportCardEnum.Ground,
            Description="The most awesome man to ever set foot in the Arena, the Wizard will blow you away with his handsomeness... and/or fireballs.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/Mej7vnv4H_3p_8qPs_N6_GKahy6HDr7pU7i9eTHS84U.png",
        },
        new TroopModel()
        {   Name="Mini P.E.K.K.A",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=4,
            HitPoints=642,
            Damage=340,
            AreaDamage=false,
            Amount=1,
            InitialLevel=3,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Fast,
            Range=0.8f,
            HitSpeed=1.6f,
            Transport = TransportCardEnum.Ground,
            Description="The Arena is a certified butterfly-free zone. No distractions for P.E.K.K.A, only destruction.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/Fmltc4j3Ve9vO_xhHHPEO3PRP3SmU2oKp2zkZQHRZT4.png",
        },
        new TroopModel()
        {   Name="Spear Goblins",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=2,
            HitPoints=52,
            Damage=32,
            AreaDamage=false,
            Amount=3,
            InitialLevel=1,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Very_Fast,
            Range=5.5f,
            HitSpeed=1.7f,
            Transport = TransportCardEnum.Ground,
            Description="Three unarmored ranged attackers. Who the heck taught these guys to throw spears!? Who thought that was a good idea?!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/FSDFotjaXidI4ku_WFpVCTWS1hKGnFh1sxX0lxM43_E.png",
        },
        new TroopModel()
        {   Name="Giant Skeleton",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=6,
            HitPoints=2140,
            Damage=167,
            AreaDamage=false,
            Amount=1,
            InitialLevel=6,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=0.8f,
            HitSpeed=1.4f,
            Transport = TransportCardEnum.Ground,
            Description="The bigger the skeleton, the bigger the bomb. Carries a bomb that blows up when the Giant Skeleton dies.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/0p0gd0XaVRu1Hb1iSG1hTYbz2AN6aEiZnhaAib5O8Z8.png",
        },
        new TroopModel()
        {   Name="Hog Rider",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=4,
            HitPoints=800,
            Damage=150,
            AreaDamage=false,
            Amount=1,
            InitialLevel=3,
            Target=TargetCardEnum.Buildings,
            Speed= SpeedCardEnum.Very_Fast,
            Range=0.8f,
            HitSpeed=1.6f,
            Transport = TransportCardEnum.Ground,
            Description="Fast melee troop that targets buildings and can jump over the river. He followed the echoing call of \"Hog Riderrrrr\" all the way through the Arena doors.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/Ubu0oUl8tZkusnkZf8Xv9Vno5IO29Y-jbZ4fhoNJ5oc.png",
        },
        new TroopModel()
        {   Name="Minion Horde",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=5,
            HitPoints=90,
            Damage=46,
            AreaDamage=false,
            Amount=6,
            InitialLevel=1,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Fast,
            Range=1.6f,
            HitSpeed=1,
            Transport = TransportCardEnum.Air,
            Description="Six fast, unarmored flying attackers. Three's a crowd, six is a horde!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/Wyjq5l0IXHTkX9Rmpap6HaH08MvjbxFp1xBO9a47YSI.png",
        },
        new TroopModel()
        {   Name="Ice Wizard",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=3,
            HitPoints=569,
            Damage=75,
            AreaDamage=true,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=5.5f,
            HitSpeed=1.7f,
            Transport = TransportCardEnum.Ground,
            Description="This chill caster throws ice shards that slow down enemies' movement and attack speed. Despite being freezing cold, he has a handlebar mustache that's too hot for TV.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/W3dkw0HTw9n1jB-zbknY2w3wHuyuLxSRIAV5fUT1SEY.png",
        },
        new TroopModel()
        {   Name="Royal Giant",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=6,
            HitPoints=1200,
            Damage=120,
            AreaDamage=false,
            Amount=1,
            InitialLevel=1,
            Target=TargetCardEnum.Buildings,
            Speed= SpeedCardEnum.Slow,
            Range=5,
            HitSpeed=1.7f,
            Transport = TransportCardEnum.Ground,
            Description="Destroying enemy buildings with his massive cannon is his job; making a raggedy blond beard look good is his passion.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/mnlRaNtmfpQx2e6mp70sLd0ND-pKPF70Cf87_agEKg4.png",
        },
        new TroopModel()
        {   Name="Guards",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=3,
            HitPoints=51,
            Damage=76,
            AreaDamage=false,
            Amount=3,
            InitialLevel=6,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Fast,
            Range=1.6f,
            HitSpeed=1,
            Transport = TransportCardEnum.Ground,
            Description="Three ruthless bone brothers with shields. Knock off their shields and all that's left are three ruthless bone brothers.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/1ArKfLJxYo6_NU_S9cAeIrfbXqWH0oULVJXedxBXQlU.png",
        },
        new TroopModel()
        {   Name="Princess",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=3,
            HitPoints=216,
            Damage=140,
            AreaDamage=true,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=9,
            HitSpeed=3,
            Transport = TransportCardEnum.Ground,
            Description="This stunning Princess shoots flaming arrows from long range. If you're feeling warm feelings towards her, it's probably because you're on fire.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/bAwMcqp9EKVIKH3ZLm_m0MqZFSG72zG-vKxpx8aKoVs.png",
        },
        new TroopModel()
        {   Name="Dark Prince",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=4,
            HitPoints=750,
            Damage=155,
            AreaDamage=true,
            Amount=1,
            InitialLevel=6,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=1.2f,
            HitSpeed=1.3f,
            Transport = TransportCardEnum.Ground,
            Description="The Dark Prince deals area damage and lets his spiked club do the talking for him - because when he does talk, it sounds like he has a bucket on his head.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/M7fXlrKXHu2IvpSGpk36kXVstslbR08Bbxcy0jQcln8.png",
        },
        new TroopModel()
        {   Name="Three Musketeer",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=9,
            HitPoints=340,
            Damage=103,
            AreaDamage=false,
            Amount=3,
            InitialLevel=3,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=6,
            HitSpeed=1,
            Transport = TransportCardEnum.Ground,
            Description="Trio of powerful, independent markswomen, fighting for justice and honor. Disrespecting them would not be just a mistake, it would be a cardinal sin!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/_J2GhbkX3vswaFk1wG-dopwiHyNc_YiPhwroiKF3Mek.png",
        },
        new TroopModel()
        {   Name="Lava Hound",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=7,
            HitPoints=3150,
            Damage=45,
            AreaDamage=false,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Buildings,
            Speed= SpeedCardEnum.Slow,
            Range=3.5f,
            HitSpeed=1.3f,
            Transport = TransportCardEnum.Air,
            Description="The Lava Hound is a majestic flying beast that attacks buildings. The Lava Pups are less majestic angry babies that attack anything.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/unicRQ975sBY2oLtfgZbAI56ZvaWz7azj-vXTLxc0r8.png",
        },
        new TroopModel()
        {   Name="Ice Spirit",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=1,
            HitPoints=90,
            Damage=43,
            AreaDamage=true,
            Amount=1,
            InitialLevel=1,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Very_Fast,
            Range=2.5f,
            HitSpeed=1,
            Transport = TransportCardEnum.Ground,
            Description="Spawns one lively little Ice Spirit to freeze a group of enemies. Stay frosty",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/lv1budiafU9XmSdrDkk0NYyqASAFYyZ06CPysXKZXlA.png",
        },
        new TroopModel()
        {   Name="Fire Spirit",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=1,
            HitPoints=90,
            Damage=81,
            AreaDamage=true,
            Amount=1,
            InitialLevel=1,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Very_Fast,
            Range=2,
            HitSpeed=1,
            Transport = TransportCardEnum.Ground,
            Description="The Fire Spirit is on a kamikaze mission to give you a warm hug. It'd be adorable if it wasn't on fire",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/16-BqusVvynIgYI8_Jci3LDC-r8AI_xaIYLgXqtlmS8.png",
        },
        new TroopModel()
        {   Name="Miner",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=3,
            HitPoints=1000,
            Damage=160,
            AreaDamage=false,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Fast,
            Range=1.2f,
            HitSpeed=1.2f,
            Transport = TransportCardEnum.Ground,
            Description="The Miner can burrow his way underground and appear anywhere in the Arena. It's not magic, it's a shovel. A shovel that deals reduced damage to Crown Towers.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/Y4yWvdwBCg2FpAZgs8T09Gy34WOwpLZW-ttL52Ae8NE.png",
        },
        new TroopModel()
        {   Name="Sparky",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=6,
            HitPoints=1200,
            Damage=1100,
            AreaDamage=true,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Slow,
            Range=5,
            HitSpeed=4,
            Transport = TransportCardEnum.Ground,
            Description="Sparky slowly charges up, then unloads MASSIVE area damage. Overkill isn't in her vocabulary.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/2GKMkBrArZXgQxf2ygFjDs4VvGYPbx8F6Lj_68iVhIM.png",
        },
        new TroopModel()
        {   Name="Bowler",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=5,
            HitPoints=1300,
            Damage=180,
            AreaDamage=true,
            Amount=1,
            InitialLevel=6,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Slow,
            Range=4,
            HitSpeed=2.5f,
            Transport = TransportCardEnum.Ground,
            Description="This big blue dude digs the simple things in life - Dark Elixir drinks and throwing rocks. His massive boulders roll through their target, hitting everything behind for a strike!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/SU4qFXmbQXWjvASxVI6z9IJuTYolx4A0MKK90sTIE88.png",
        },
        new TroopModel()
        {   Name="Lumberjack",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=4,
            HitPoints=1060,
            Damage=200,
            AreaDamage=false,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Very_Fast,
            Range=0.7f,
            HitSpeed=0.8f,
            Transport = TransportCardEnum.Ground,
            Description="He chops trees by day and hunts The Log by night. His bottle of Rage spills everywhere when he's defeated.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/E6RWrnCuk13xMX5OE1EQtLEKTZQV6B78d00y8PlXt6Q.png",
        },
        new TroopModel()
        {   Name="Battle Ram",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=4,
            HitPoints=456,
            Damage=135,
            AreaDamage=false,
            Amount=1,
            InitialLevel=3,
            Target=TargetCardEnum.Buildings,
            Speed= SpeedCardEnum.Medium,
            Range=0.5f,
            HitSpeed=1,
            Transport = TransportCardEnum.Ground,
            Description="Two Barbarians holding a big log charge at the nearest building, dealing significant damage if they connect; then they go to town with their swords!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/dyc50V2cplKi4H7pq1B3I36pl_sEH5DQrNHboS_dbbM.png",
        },
        new TroopModel()
        {   Name="Inferno Dragon",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=4,
            HitPoints=1070,
            Damage=30,
            AreaDamage=false,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=3.5f,
            HitSpeed=0.4f,
            Transport = TransportCardEnum.Air,
            Description="Shoots a focused beam of fire that increases in damage over time. Wears a helmet because flying can be dangerous.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/y5HDbKtTbWG6En6TGWU0xoVIGs1-iQpIP4HC-VM7u8A.png",
        },
        new TroopModel()
        {   Name="Ice Golem",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=2,
            HitPoints=565,
            Damage=40,
            AreaDamage=false,
            Amount=1,
            InitialLevel=3,
            Target=TargetCardEnum.Buildings,
            Speed= SpeedCardEnum.Slow,
            Range=3.5f,
            HitSpeed=0.4f,
            Transport = TransportCardEnum.Ground,
            Description="He's tough, targets buildings and explodes when destroyed, slowing nearby enemies. Made entirely out of ice... or is he?! Yes.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/r05cmpwV1o7i7FHodtZwW3fmjbXCW34IJCsDEV5cZC4.png",
        },
        new TroopModel()
        {   Name="Mega Minion",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=3,
            HitPoints=395,
            Damage=147,
            AreaDamage=false,
            Amount=1,
            InitialLevel=3,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=1.6f,
            HitSpeed=1.5f,
            Transport = TransportCardEnum.Air,
            Description="Flying, armored and powerful. What could be its weakness?! Cupcakes.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/-T_e4YLbuhPBKbYnBwQfXgynNpp5eOIN_0RracYwL9c.png",
        },
        new TroopModel()
        {   Name="Dart Goblin",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=3,
            HitPoints=123,
            Damage=62,
            AreaDamage=false,
            Amount=1,
            InitialLevel=3,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Very_Fast,
            Range=6.5f,
            HitSpeed=0.7f,
            Transport = TransportCardEnum.Ground,
            Description="Runs fast, shoots far and chews gum. How does he blow darts with a mouth full of Double Trouble gum? Years of didgeridoo lessons.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/BmpK3bqEAviflqHCdxxnfm-_l3pRPJw3qxHkwS55nCY.png",
        },
        new TroopModel()
        {   Name="Goblin Gang",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=3,
            HitPoints=79,
            Damage=47,
            AreaDamage=false,
            Amount=6,
            InitialLevel=1,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Very_Fast,
            Range=9.5f,
            HitSpeed=1.1f,
            Transport = TransportCardEnum.Ground,
            Description="Spawns Six Goblins - three with knives, three with spears - at a discounted Elixir cost. It's like a Goblin Value Pack!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/NHflxzVAQT4oAz7eDfdueqpictb5vrWezn1nuqFhE4w.png",
        },
        new TroopModel()
        {   Name="Electro Wizard",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=4,
            HitPoints=590,
            Damage=182,
            AreaDamage=false,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Fast,
            Range=5,
            HitSpeed=1.8f,
            Transport = TransportCardEnum.Ground,
            Description="He lands with a \"POW!\", stuns nearby enemies and shoots lightning with both hands! What a show off.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/RsFaHgB3w6vXsTjXdPr3x8l_GbV9TbOUCvIx07prbrQ.png",
        },
        new TroopModel()
        {   Name="Elite Barbarians",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=6,
            HitPoints=524,
            Damage=150,
            AreaDamage=false,
            Amount=2,
            InitialLevel=1,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Fast,
            Range=1.2f,
            HitSpeed=1.4f,
            Transport = TransportCardEnum.Ground,
            Description="Spawns a pair of leveled up Barbarians. They're like regular Barbarians, only harder, better, faster and stronger.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/C88C5JH_F3lLZj6K-tLcMo5DPjrFmvzIb1R2M6xCfTE.png",
        },
        new TroopModel()
        {   Name="Hunter",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=4,
            HitPoints=524,
            Damage=530,
            AreaDamage=true,
            Amount=1,
            InitialLevel=6,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=4,
            HitSpeed=2.2f,
            Transport = TransportCardEnum.Ground,
            Description="He deals BIG damage up close - not so much at range. What he lacks in accuracy, he makes up for with his impressively bushy eyebrows.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/VNabB1WKnYtYRSG7X_FZfnZjQDHTBs9A96OGMFmecrA.png",
        },
        new TroopModel()
        {   Name="Executioner",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=5,
            HitPoints=800,
            Damage=212,
            AreaDamage=true,
            Amount=1,
            InitialLevel=6,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=4.5f,
            HitSpeed=0.9f,
            Transport = TransportCardEnum.Ground,
            Description="He throws his axe like a boomerang, striking all enemies on the way out AND back. It's a miracle he doesn't lose an arm.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/9XL5BP2mqzV8kza6KF8rOxrpCZTyuGLp2l413DTjEoM.png",
        },
        new TroopModel()
        {   Name="Bandit",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=3,
            HitPoints=750,
            Damage=160,
            AreaDamage=false,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Fast,
            Range=0.75f,
            HitSpeed=1,
            Transport = TransportCardEnum.Ground,
            Description="The Bandit dashes to her target and delivers an extra big hit! While dashing, she can't be touched. The mask keeps her identity safe, and gives her bonus cool points!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/QWDdXMKJNpv0go-HYaWQWP6p8uIOHjqn-zX7G0p3DyM.png",
        },
        new TroopModel()
        {   Name="Royal Recruits",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=7,
            HitPoints=208,
            Damage=52,
            AreaDamage=false,
            Amount=6,
            InitialLevel=1,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=1.6f,
            HitSpeed=1.3f,
            Transport = TransportCardEnum.Ground,
            Description="Deploys a line of recruits armed with spears, shields and wooden buckets. They dream of ponies and one day wearing metal buckets.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/jcNyYGUiXXNz3kuz8NBkHNKNREQKraXlb_Ts7rhCIdM.png",
        },
        new TroopModel()
        {   Name="Night Witch",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=4,
            HitPoints=750,
            Damage=260,
            AreaDamage=false,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=1.6f,
            HitSpeed=1.3f,
            Transport = TransportCardEnum.Ground,
            Description="Summons Bats to do her bidding! If you get too close, she's not afraid of pitching in with her mean-looking battle staff.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/NpCrXDEDBBJgNv9QrBAcJmmMFbS7pe3KCY8xJ5VB18A.png",
        },
        new TroopModel()
        {   Name="Bats",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=2,
            HitPoints=32,
            Damage=32,
            AreaDamage=false,
            Amount=5,
            InitialLevel=1,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Very_Fast,
            Range=1.2f,
            HitSpeed=1.3f,
            Transport = TransportCardEnum.Air,
            Description="Spawns a handful of tiny flying creatures. Think of them as sweet, purple... balls of DESTRUCTION!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/EnIcvO21hxiNpoI-zO6MDjLmzwPbq8Z4JPo2OKoVUjU.png",
        },
        new TroopModel()
        {   Name="Royal Ghost",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=3,
            HitPoints=1000,
            Damage=216,
            AreaDamage=true,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Fast,
            Range=1.2f,
            HitSpeed=1.8f,
            Transport = TransportCardEnum.Ground,
            Description="He drifts invisibly through the Arena until he's startled by an enemy... then he attacks! Then he's invisible again! Zzzz.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/3En2cz0ISQAaMTHY3hj3rTveFN2kJYq-H4VxvdJNvCM.png",
        },
        new TroopModel()
        {   Name="Ram Rider",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=5,
            HitPoints=1461,
            Damage=220,
            AreaDamage=false,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Buildings,
            Speed= SpeedCardEnum.Medium,
            Range=0.8f,
            HitSpeed=1.8f,
            Transport = TransportCardEnum.Ground,
            Description="Together they charge through the Arena; snaring enemies, knocking down towers... and chewing grass!?",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/QaJyerT7f7oMyZ3Fv1glKymtLSvx7YUXisAulxl7zRI.png",
        },
        new TroopModel()
        {   Name="Zappies",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=4,
            HitPoints=250,
            Damage=45,
            AreaDamage=false,
            Amount=3,
            InitialLevel=3,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=4.5f,
            HitSpeed=2.1f,
            Transport = TransportCardEnum.Ground,
            Description="Spawns a pack of miniature Zap machines. Who controls them...? Only the Master Builder knows.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/QZfHRpLRmutZbCr5fpLnTpIp89vLI6NrAwzGZ8tHEc4.png",
        },
        new TroopModel()
        {   Name="Rascals",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=5,
            HitPoints=758,
            Damage=52,
            AreaDamage=false,
            Amount=3,
            InitialLevel=1,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=0.8f,
            HitSpeed=1.5f,
            Transport = TransportCardEnum.Ground,
            Description="Spawns a mischievous trio of Rascals! The boy takes the lead, while the girls pelt enemies from behind... with slingshots full of Double Trouble Gum!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/KV48DfwVHKx9XCjzBdk3daT_Eb52Me4VgjVO7WctRc4.png",
        },
        new TroopModel()
        {   Name="Cannon Cart",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=5,
            HitPoints=513,
            Damage=133,
            AreaDamage=false,
            Amount=1,
            InitialLevel=6,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=5.5f,
            HitSpeed=1,
            Transport = TransportCardEnum.Ground,
            Description="A Cannon on wheels?! Bet they won't see that coming! Once you break its shield, it becomes a Cannon not on wheels.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/aqwxRz8HXzqlMCO4WMXNA1txynjXTsLinknqsgZLbok.png",
        },
        new TroopModel()
        {   Name="Mega Knight",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=7,
            HitPoints=3300,
            Damage=222,
            AreaDamage=true,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=1.2f,
            HitSpeed=1.7f,
            Transport = TransportCardEnum.Ground,
            Description="He lands with the force of 1,000 mustaches, then jumps from one foe to the next dealing huge area damage. Stand aside!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/O2NycChSNhn_UK9nqBXUhhC_lILkiANzPuJjtjoz0CE.png",
        },
        new TroopModel()
        {   Name="Skeleton Barrel",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=3,
            HitPoints=208,
            Damage=52,
            AreaDamage=true,
            Amount=1,
            InitialLevel=1,
            Target=TargetCardEnum.Buildings,
            Speed= SpeedCardEnum.Fast,
            Range=0.35f,
            HitSpeed=1,
            Transport = TransportCardEnum.Air,
            Description="It's a Skeleton party in the sky, until all the balloons pop... then it's a Skeleton party on the ground!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/vCB4DWCcrGbTkarjcOiVz4aNDx6GWLm0yUepg9E1MGo.png",
        },
        new TroopModel()
        {   Name="Flying Machine",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=4,
            HitPoints=290,
            Damage=81,
            AreaDamage=false,
            Amount=1,
            InitialLevel=3,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Fast,
            Range=6,
            HitSpeed=1.1f,
            Transport = TransportCardEnum.Air,
            Description="The Master Builder has sent his first contraption to the Arena! It's a fast and fun flying machine, but fragile!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/hzKNE3QwFcrSrDDRuVW3QY_OnrDPijSiIp-PsWgFevE.png",
        },
        new TroopModel()
        {   Name="Wall Breakers",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=2,
            HitPoints=207,
            Damage=245,
            AreaDamage=true,
            Amount=2,
            InitialLevel=6,
            Target=TargetCardEnum.Buildings,
            Speed= SpeedCardEnum.Very_Fast,
            Range=0.5f,
            HitSpeed=1,
            Transport = TransportCardEnum.Ground,
            Description="A daring duo of dangerous dive bombers. Nothing warms a Wall Breaker's cold and undead heart like blowing up buildings.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/hzKNE3QwFcrSrDDRuVW3QY_OnrDPijSiIp-PsWgFevE.png",
        },
        new TroopModel()
        {   Name="Royal Hogs",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=5,
            HitPoints=395,
            Damage=35,
            AreaDamage=false,
            Amount=4,
            InitialLevel=3,
            Target=TargetCardEnum.Buildings,
            Speed= SpeedCardEnum.Very_Fast,
            Range=0.7f,
            HitSpeed=1.2f,
            Transport = TransportCardEnum.Ground,
            Description="The King’s personal pets are loose! They love to chomp on apples and towers alike - who let the hogs out?!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/ASSQJG_MoVq9e81HZzo4bynMnyLNpNJMfSLb3hqydOw.png",
        },
        new TroopModel()
        {   Name="Goblin Giant",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=6,
            HitPoints=2085,
            Damage=110,
            AreaDamage=false,
            Amount=1,
            InitialLevel=6,
            Target=TargetCardEnum.Buildings,
            Speed= SpeedCardEnum.Medium,
            Range=1.2f,
            HitSpeed=1.5f,
            Transport = TransportCardEnum.Ground,
            Description="This jolly green Goblin Giant stomps towards enemy buildings. He carries two Spear Goblins everywhere he goes. It's a weird but functional arrangement.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/SoW16cY3jXBwaTDvb39DkqiVsoFVaDWbzf5QBYphJrY.png",
        },
        new TroopModel()
        {   Name="Fisherman",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=3,
            HitPoints=720,
            Damage=160,
            AreaDamage=false,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=1.2f,
            HitSpeed=1.3f,
            Transport = TransportCardEnum.Ground,
            Description="His Ranged Attack can pull enemies towards him, and pull himself to enemy buildings. He's also mastered the ancient art of 'Fish Slapping'.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/U2KZ3g0wyufcuA5P2Xrn3Z3lr1WiJmc5S0IWOZHgizQ.png",
        },
        new TroopModel()
        {   Name="Magic Archer",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=4,
            HitPoints=440,
            Damage=111,
            AreaDamage=true,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=7,
            HitSpeed=1.1f,
            Transport = TransportCardEnum.Ground,
            Description="Not quite a Wizard, nor an Archer - he shoots a magic arrow that passes through and damages all enemies in its path. It's not a trick, it's magic!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/Avli3W7BxU9HQ2SoLiXnBgGx25FoNXUSFm7OcAk68ek.png",
        },
        new TroopModel()
        {   Name="Electro Dragon",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=5,
            HitPoints=594,
            Damage=360,
            AreaDamage=true,
            Amount=1,
            InitialLevel=6,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=3.5f,
            HitSpeed=2.1f,
            Transport = TransportCardEnum.Air,
            Description="Spits out bolts of electricity hitting up to three targets. Suffers from middle child syndrome to boot.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/tN9h6lnMNPCNsx0LMFmvpHgznbDZ1fBRkx-C7UfNmfY.png",
        },
        new TroopModel()
        {   Name="Firecracker",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=3,
            HitPoints=119,
            Damage=125,
            AreaDamage=true,
            Amount=1,
            InitialLevel=1,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Fast,
            Range=6,
            HitSpeed=3,
            Transport = TransportCardEnum.Ground,
            Description="Shoots a firework that explodes on impact, damaging the target and showering anything behind it with sparks. This is what happens when Archers get bored!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/c1rL3LO1U2D9-TkeFfAC18gP3AO8ztSwrcHMZplwL2Q.png",
        },
        new TroopModel()
        {   Name="Mighty Miner",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Champion,
            Elixir=4,
            HitPoints=2250,
            Damage=40,
            AreaDamage=false,
            Amount=1,
            InitialLevel=11,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=1.6f,
            HitSpeed=0.4f,
            Transport = TransportCardEnum.Ground,
            Description="Walk softly... and carry a big drill! This Champion deals increasing Damage to his target and can switch lanes to escape combat or change attack plans. This makes him not only the mightiest, but also the sneakiest Miner in the Arena.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/Cd9R56yraxTvJiD8xJ2qT2OdsHyh94FqOAarXpbyelo.png",
        },
        new TroopModel()
        {   Name="Elixir Golem",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=3,
            HitPoints=740,
            Damage=120,
            AreaDamage=false,
            Amount=1,
            InitialLevel=3,
            Target=TargetCardEnum.Buildings,
            Speed= SpeedCardEnum.Slow,
            Range=0.8f,
            HitSpeed=1.1f,
            Transport = TransportCardEnum.Ground,
            Description="Splits into two Elixir Golemites when destroyed, which split into two sentient Blobs when defeated. Each part of the Elixir Golem gives your opponent some Elixir when destroyed!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/puhMsZjCIqy21HW3hYxjrk_xt8NIPyFqjRy-BeLKZwo.png",
        },
        new TroopModel()
        {   Name="Battle Healer",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=4,
            HitPoints=810,
            Damage=70,
            AreaDamage=false,
            Amount=1,
            InitialLevel=3,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=1.6f,
            HitSpeed=1.5f,
            Transport = TransportCardEnum.Ground,
            Description="With each attack, she unleashes a powerful healing aura that restores Hitpoints to herself and friendly Troops. When she isn't attacking, she passively heals herself!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/KdwXcoigS2Kg-cgA7BJJIANbUJG6SNgjetRQ-MegZ08.png",
        },
        new TroopModel()
        {   Name="Skeleton King",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Champion,
            Elixir=4,
            HitPoints=2300,
            Damage=205,
            AreaDamage=true,
            Amount=1,
            InitialLevel=11,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=1.2f,
            HitSpeed=1.6f,
            Transport = TransportCardEnum.Ground,
            Description="The King of the undead himself. He sometimes feels lonely (could be due to his non flattering features) and will summon friends to join him in the battle even after death. Tough guys have feelings too!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/dCd69_wN9f8DxwuqOGtR4QgWhHIPIaTNxZ1e23RzAAc.png",
        },
        new TroopModel()
        {   Name="Archer Queen",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Champion,
            Elixir=5,
            HitPoints=1000,
            Damage=225,
            AreaDamage=false,
            Amount=1,
            InitialLevel=11,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=5,
            HitSpeed=1.2f,
            Transport = TransportCardEnum.Ground,
            Description="She is fast, deadly and hard to catch. Beware of her crossbow bolts and try not to blink - you might miss her!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/p7OQmOAFTery7zCzlpDdm-LOD1kINTm42AwIHchZfWk.png",
        },
        new TroopModel()
        {   Name="Golden Knight",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Champion,
            Elixir=4,
            HitPoints=1800,
            Damage=160,
            AreaDamage=false,
            Amount=1,
            InitialLevel=11,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=1.2f,
            HitSpeed=0.9f,
            Transport = TransportCardEnum.Ground,
            Description="A warrior with luxurious hair and outstanding flexibility. Demonstrates his aerobics skills on demand.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/WJd207D0O1sN-l1FTb8P9KhYL2oF5jY26vRUfTUW3FQ.png",
        },
        new TroopModel()
        {   Name="Monk",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Champion,
            Elixir=5,
            HitPoints=2000,
            Damage=140,
            AreaDamage=false,
            Amount=1,
            InitialLevel=11,
            Target=TargetCardEnum.Ground,
            Speed= SpeedCardEnum.Medium,
            Range=1.2f,
            HitSpeed=0.8f,
            Transport = TransportCardEnum.Ground,
            Description="Monk has spent many isolated years perfecting a new style of combat. He fires off a 3-hit combo, with the last blow dealing extra Damage and pushing enemies back!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/2onG4t4-CxqwFVZAn6zpWxFz3_mG2ksSj4Q7zldo1SM.png",
        },
        new TroopModel()
        {   Name="Skeleton Dragons",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=4,
            HitPoints=220,
            Damage=63,
            AreaDamage=true,
            Amount=2,
            InitialLevel=1,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Fast,
            Range=3.5f,
            HitSpeed=1.9f,
            Transport = TransportCardEnum.Air,
            Description="This pair of skeletal scorchers deal Area Damage and fly above the Arena. They also play a mean rib cage xylophone duet.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/qPOtg9uONh47_NLxGhhFc_ww9PlZ6z3Ry507q1NZUXs.png",
        },
        new TroopModel()
        {   Name="Mother Witch",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=4,
            HitPoints=440,
            Damage=110,
            AreaDamage=false,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=5.5f,
            HitSpeed=1,
            Transport = TransportCardEnum.Ground,
            Description="Places a curse on enemy troops with each attack. When a cursed troop is destroyed, it turns into a building-targeting Hog that fights alongside the Mother Witch. She also bakes great cookies.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/fO-Xah8XZkYKaSK9SCp3wnzwxtvIhun9NVY-zzte1Ng.png",
        },
        new TroopModel()
        {   Name="Electro Spirit",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Common,
            Elixir=1,
            HitPoints=90,
            Damage=39,
            AreaDamage=false,
            Amount=1,
            InitialLevel=1,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Very_Fast,
            Range=2.5f,
            HitSpeed=1,
            Transport = TransportCardEnum.Ground,
            Description="Jumps on enemies, dealing Area damage and stunning up to 9 enemy Troops. Locked in an eternal battle with Knight for the best mustache",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/WKd4-IAFsgPpMo7dDi9sujmYjRhOMEWiE07OUJpvD9g.png",
        },
        new TroopModel()
        {   Name="Electro Giant",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Epic,
            Elixir=7,
            HitPoints=2410,
            Damage=102,
            AreaDamage=false,
            Amount=1,
            InitialLevel=6,
            Target=TargetCardEnum.Buildings,
            Speed= SpeedCardEnum.Slow,
            Range=1.2f,
            HitSpeed=2.1f,
            Transport = TransportCardEnum.Ground,
            Description="He channels electricity through his Zap Pack, a unique device that stuns and damages any troop attacking him within its range. Don't tell him that his finger guns aren't real! He'll zap you.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/_uChZkNHAMq6tPb3v6A49xinOe3CnhjstOhG6OZbPYc.png",
        },
        new TroopModel()
        {   Name="Phoenix",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Legendary,
            Elixir=4,
            HitPoints=870,
            Damage=180,
            AreaDamage=false,
            Amount=1,
            InitialLevel=9,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Medium,
            Range=1.6f,
            HitSpeed=1,
            Transport = TransportCardEnum.Air,
            Description="This mystical creature will be reborn as an egg when destroyed. If it hatches, it returns to the fight! What an egg-cellent ability. Being born again is tiring, so a hatched Phoenix will have slightly less Hitpoints and Damage (80% of its total).",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/i0RoY1fs6ay7VAxyFEfZGIPnD002nAKcne9FtJsWBHM.png",
        },
        new TroopModel()
        {   Name="Heal Spirit",
            Type = TypeCardEnum.Troop,
            Quality = QualityCardEnum.Rare,
            Elixir=1,
            HitPoints=109,
            Damage=52,
            AreaDamage=true,
            Amount=1,
            InitialLevel=3,
            Target=TargetCardEnum.Ground_Air,
            Speed= SpeedCardEnum.Very_Fast,
            Range=2.5f,
            HitSpeed=1,
            Transport = TransportCardEnum.Ground,
            Description="A mischevious Spirit that leaps at enemies, dealing Damage and leaving behind a powerful healing effect that restores Hitpoints to friendly Troops!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/GITl06sa2nGRLPvboyXbGEv5E3I-wAwn1Eqa5esggbc.png",
        },
    };
    public static List<SpellModel> SpellCards { get; } = new List<SpellModel>()
    {
        new SpellModel()
        {
            Name="FireBall",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Rare,
            Elixir=4,
            LifeTime=0,
            Damage=325,
            TowerDamage = 97,
            AreaDamage=true,
            InitialLevel=3,
            Target = TargetCardEnum.Ground_Air,
            Radius=2.5f,
            Description="Annnnnd... Fireball. Incinerates a small area, dealing high damage. Reduced damage to Crown Towers.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/lZD9MILQv7O-P3XBr_xOLS5idwuz3_7Ws9G60U36yhc.png"
        },
        new SpellModel()
        {
            Name="Arrows",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Common,
            Elixir=4,
            LifeTime=0,
            Damage=144,
            TowerDamage = 42,
            AreaDamage=true,
            InitialLevel=1,
            Target = TargetCardEnum.Ground_Air,
            Radius=4,
            Description="Arrows pepper a large area, damaging all enemies hit. Reduced damage to Crown Towers.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/Flsoci-Y6y8ZFVi5uRFTmgkPnCmMyMVrU7YmmuPvSBo.png"
        },
        new SpellModel()
        {
            Name="Rage",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Epic,
            Elixir=2,
            LifeTime=6,
            Damage=120,
            TowerDamage = 36,
            AreaDamage=true,
            InitialLevel=6,
            Target = TargetCardEnum.Ground_Air,
            Radius=3,
            Description="Increases troop movement and attack speed. Buildings attack faster and summon troops quicker, too. Chaaaarge!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/bGP21OOmcpHMJ5ZA79bHVV2D-NzPtDkvBskCNJb7pg0.png"
        },
        new SpellModel()
        {
            Name="Rocket",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Rare,
            Elixir=6,
            LifeTime=0,
            Damage=700,
            TowerDamage = 175,
            AreaDamage=true,
            InitialLevel=3,
            Target = TargetCardEnum.Ground_Air,
            Radius=2,
            Description="Deals high damage to a small area. Looks really awesome doing it. Reduced damage to Crown Towers.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/Ie07nQNK9CjhKOa4-arFAewi4EroqaA-86Xo7r5tx94.png"
        },
        new SpellModel()
        {
            Name="Goblin Barrel",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Epic,
            Elixir=3,
            LifeTime=0,
            Damage=0,
            TowerDamage = 0,
            AreaDamage=false,
            InitialLevel=6,
            Target = TargetCardEnum.Nothing,
            Radius=1.5f,
            Description="Spawns three Goblins anywhere in the Arena. It's going to be a thrilling ride, boys!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/CoZdp5PpsTH858l212lAMeJxVJ0zxv9V-f5xC8Bvj5g.png"
        },
        new SpellModel()
        {
            Name="Freeze",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Epic,
            Elixir=4,
            LifeTime=4,
            Damage=72,
            TowerDamage = 21,
            AreaDamage=true,
            InitialLevel=6,
            Target = TargetCardEnum.Ground_Air,
            Radius=3,
            Description="Freezes and damages enemy troops and buildings, making them unable to move or attack. Everybody chill. Reduced damage to Crown Towers.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/I1M20_Zs_p_BS1NaNIVQjuMJkYI_1-ePtwYZahn0JXQ.png"
        },
        new SpellModel()
        {
            Name="Mirror",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Epic,
            Elixir=0,
            LifeTime=0,
            Damage=0,
            TowerDamage = 0,
            AreaDamage=false,
            InitialLevel=6,
            Target = TargetCardEnum.Nothing,
            Radius=0,
            Description="Mirrors your last card played for +1 Elixir. Does not appear in your starting hand.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/wC6Cm9rKLEOk72zTsukVwxewKIoO4ZcMJun54zCPWvA.png"
        },
        new SpellModel()
        {
            Name="Lightning",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Epic,
            Elixir=6,
            LifeTime=2,
            Damage=660,
            TowerDamage = 198,
            AreaDamage=false,
            InitialLevel=6,
            Target = TargetCardEnum.Ground_Air,
            Radius=3.5f,
            Description="Bolts of lightning damage and stun up to three enemy troops or buildings with the most hitpoints in the target area. Reduced damage to Crown Towers.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/fpnESbYqe5GyZmaVVYe-SEu7tE0Kxh_HZyVigzvLjks.png"
        },
        new SpellModel()
        {
            Name="Zap",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Common,
            Elixir=2,
            LifeTime=0,
            Damage=75,
            TowerDamage = 22,
            AreaDamage=true,
            InitialLevel=1,
            Target = TargetCardEnum.Ground_Air,
            Radius=2.5f,
            Description="Zaps enemies, briefly stunning them and dealing damage inside a small radius. Reduced damage to Crown Towers.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/7dxh2-yCBy1x44GrBaL29vjqnEEeJXHEAlsi5g6D1eY.png"
        },
        new SpellModel()
        {
            Name="Poison",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Epic,
            Elixir=2,
            LifeTime=8,
            Damage=57,
            TowerDamage = 17,
            AreaDamage=true,
            InitialLevel=6,
            Target = TargetCardEnum.Ground_Air,
            Radius=3.5f,
            Description="Covers the area in a deadly toxin, damaging enemy troops and buildings over time. Yet somehow leaves the grass green and healthy. Go figure! Reduced damage to Crown Towers.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/98HDkG2189yOULcVG9jz2QbJKtfuhH21DIrIjkOjxI8.png"
        },
        new SpellModel()
        {
            Name="Graveyard",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Legendary,
            Elixir=5,
            LifeTime=10,
            Damage=0,
            TowerDamage = 0,
            AreaDamage=false,
            InitialLevel=9,
            Target = TargetCardEnum.Nothing,
            Radius=4,
            Description="Surprise! It's a party. A Skeleton party, anywhere in the Arena. Yay!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/Icp8BIyyfBTj1ncCJS7mb82SY7TPV-MAE-J2L2R48DI.png"
        },
        new SpellModel()
        {
            Name="The Log",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Legendary,
            Elixir=2,
            LifeTime=2,
            Damage=240,
            TowerDamage = 48,
            AreaDamage=true,
            InitialLevel=9,
            Target = TargetCardEnum.Ground,
            Radius=3.9f,
            Description="A spilt bottle of Rage turned an innocent tree trunk into \"The Log\". Now, it seeks revenge by crushing anything in its path! Reduced damage to Crown Towers.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/_iDwuDLexHPFZ_x4_a0eP-rxCS6vwWgTs6DLauwwoaY.png"
        },
        new SpellModel()
        {
            Name="Tornado",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Epic,
            Elixir=3,
            LifeTime=1,
            Damage=106,
            TowerDamage = 36,
            AreaDamage=true,
            InitialLevel=6,
            Target = TargetCardEnum.Ground_Air,
            Radius=5.5f,
            Description="Drags enemy troops to its center while dealing damage over time, just like a magnet. A big, swirling, Tornado-y magnet.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/QJB-QK1QJHdw4hjpAwVSyZBozc2ZWAR9pQ-SMUyKaT0.png"
        },
        new SpellModel()
        {
            Name="Clone",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Epic,
            Elixir=3,
            LifeTime=0,
            Damage=0,
            TowerDamage = 0,
            AreaDamage=false,
            InitialLevel=6,
            Target = TargetCardEnum.Ground_Air,
            Radius=3,
            Description="Duplicates all friendly troops in the target area. Cloned troops are fragile, but pack the same punch as the original! Doesn't affect buildings.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/mHVCet-1TkwWq-pxVIU2ZWY9_2z7Z7wtP25ArEUsP_g.png"
        },
        new SpellModel()
        {
            Name="Earthquake",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Rare,
            Elixir=3,
            LifeTime=3,
            Damage=39,
            TowerDamage = 25,
            AreaDamage=true,
            InitialLevel=3,
            Target = TargetCardEnum.Ground,
            Radius=3.5f,
            Description="Deals Damage per second to Troops and Crown Towers. Deals huge Building Damage! Does not affect flying units (it is an EARTHquake, after all).",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/XeQXcrUu59C52DslyZVwCnbi4yamID-WxfVZLShgZmE.png"
        },
        new SpellModel()
        {
            Name="Barbarian Barrel",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Epic,
            Elixir=2,
            LifeTime=1,
            Damage=151,
            TowerDamage = 0,
            AreaDamage=true,
            InitialLevel=6,
            Target = TargetCardEnum.Ground,
            Radius=2.6f,
            Description="It rolls over and damages anything in its path, then breaks open and out pops a Barbarian! How did he get inside?!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/Gb0G1yNy0i5cIGUHin8uoFWxqntNtRPhY_jeMXg7HnA.png"
        },
        new SpellModel()
        {
            Name="Giant Snowball",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Common,
            Elixir=2,
            LifeTime=0,
            Damage=75,
            TowerDamage = 22,
            AreaDamage=true,
            InitialLevel=1,
            Target = TargetCardEnum.Ground_Air,
            Radius=2.5f,
            Description="It’s HUGE! Once it began rolling down Frozen Peak, there was no stopping it. Enemies hit are knocked back and slowed down. Reduced damage to Crown Towers.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/7MaJLa6hK9WN2_VIshuh5DIDfGwm0wEv98gXtAxLDPs.png"
        },
        new SpellModel()
        {
            Name="Royal Delivery",
            Type = TypeCardEnum.Spell,
            Quality = QualityCardEnum.Common,
            Elixir=3,
            LifeTime=0,
            Damage=75,
            TowerDamage = 0,
            AreaDamage=true,
            InitialLevel=1,
            Target = TargetCardEnum.Ground_Air,
            Radius=3,
            Description="No need to sign for this package! Dropped from the sky, it deals Area Damage to enemy Troops before delivering a Royal Recruit. The empty box is also handy for espionage.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/7MaJLa6hK9WN2_VIshuh5DIDfGwm0wEv98gXtAxLDPs.png"
        }
    };
    public static List<StructureModel> StructureCards { get; } = new List<StructureModel>()
    {
        new StructureModel()
        {
            Name="Cannon",
            Type = TypeCardEnum.Structure,
            Quality = QualityCardEnum.Common,
            Elixir=3,
            HitPoints=322,
            LifeTime=30,
            Damage=83,
            AreaDamage=false,
            InitialLevel=1,
            Target = TargetCardEnum.Ground,
            Radius=3,
            Range=5.5f,
            HitSpeed=0.9f,
            Description="Defensive building. Shoots cannonballs with deadly effect, but cannot target flying troops.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/nZK1y-beLxO5vnlyUhK6-2zH2NzXJwqykcosqQ1cmZ8.png"
        },
        new StructureModel()
        {
            Name="Goblin Hut",
            Type = TypeCardEnum.Structure,
            Quality = QualityCardEnum.Rare,
            Elixir=5,
            HitPoints=400,
            LifeTime=29,
            Damage=0,
            AreaDamage=false,
            InitialLevel=3,
            Target = TargetCardEnum.Nothing,
            Radius=3,
            Range=0,
            HitSpeed=0,
            Description="Building that spawns Spear Goblins. Don't look inside... You don't want to see how they're made.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/l8ZdzzNLcwB4u7ihGgxNFQOjCT_njFuAhZr7D6PRF7E.png"
        },
        new StructureModel()
        {
            Name="Mortar",
            Type = TypeCardEnum.Structure,
            Quality = QualityCardEnum.Common,
            Elixir=4,
            HitPoints=535,
            LifeTime=30,
            Damage=104,
            AreaDamage=true,
            InitialLevel=1,
            Target = TargetCardEnum.Ground,
            Radius=2,
            Range=11.5f,
            HitSpeed=5,
            Description="Defensive building with a long range. Shoots big boulders that deal area damage, but cannot hit targets that get very close!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/lPOSw6H7YOHq2miSCrf7ZDL3ANjhJdPPDYOTujdNrVE.png"
        },
        new StructureModel()
        {
            Name="Inferno Tower",
            Type = TypeCardEnum.Structure,
            Quality = QualityCardEnum.Rare,
            Elixir=5,
            HitPoints=825,
            LifeTime=30,
            Damage=20,
            AreaDamage=false,
            InitialLevel=3,
            Target = TargetCardEnum.Ground_Air,
            Radius=3,
            Range=6,
            HitSpeed=0.4f,
            Description="Defensive building, roasts targets for damage that increases over time. Burns through even the biggest and toughest enemies!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/GSHY_wrooMMLET6bG_WJB8redtwx66c4i80ipi4gYOM.png"
        },
        new StructureModel()
        {
            Name="Bomb Tower",
            Type = TypeCardEnum.Structure,
            Quality = QualityCardEnum.Rare,
            Elixir=4,
            HitPoints=640,
            LifeTime=30,
            Damage=105,
            AreaDamage=true,
            InitialLevel=3,
            Target = TargetCardEnum.Ground,
            Radius=3,
            Range=6,
            HitSpeed=1.6f,
            Description="Defensive building that houses a Bomber. Deals area damage to anything dumb enough to stand near it.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/rirYRyHPc97emRjoH-c1O8uZCBzPVnToaGuNGusF3TQ.png"
        },
        new StructureModel()
        {
            Name="Barbarian Hut",
            Type = TypeCardEnum.Structure,
            Quality = QualityCardEnum.Rare,
            Elixir=6,
            HitPoints=550,
            LifeTime=30,
            Damage=0,
            AreaDamage=false,
            InitialLevel=3,
            Target = TargetCardEnum.Nothing,
            Radius=3,
            Range=0,
            HitSpeed=0,
            Description="Building that periodically spawns Barbarians to fight the enemy. Time to make the Barbarians!",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/ho0nOG2y3Ch86elHHcocQs8Fv_QNe0cFJ2CijsxABZA.png"
        },
        new StructureModel()
        {
            Name="Tesla",
            Type = TypeCardEnum.Structure,
            Quality = QualityCardEnum.Common,
            Elixir=4,
            HitPoints=450,
            LifeTime=30,
            Damage=90,
            AreaDamage=false,
            InitialLevel=1,
            Target = TargetCardEnum.Ground_Air,
            Radius=2,
            Range=5.5f,
            HitSpeed=1.1f,
            Description="Defensive building. Whenever it's not zapping the enemy, the power of Electrickery is best kept grounded.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/OiwnGrxFMNiHetYEerE-UZt0L_uYNzFY7qV_CA_OxR4.png"
        },
        new StructureModel()
        {
            Name="Elixir Collector",
            Type = TypeCardEnum.Structure,
            Quality = QualityCardEnum.Rare,
            Elixir=6,
            HitPoints=505,
            LifeTime=65,
            Damage=0,
            AreaDamage=false,
            InitialLevel=3,
            Target = TargetCardEnum.Nothing,
            Radius=3,
            Range=0,
            HitSpeed=0,
            Description="You gotta spend Elixir to make Elixir! This building makes 8 Elixir over its Lifetime. Does not appear in your starting hand.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/BGLo3Grsp81c72EpxLLk-Sofk3VY56zahnUNOv3JcT0.png"
        },
        new StructureModel()
        {
            Name="X-Bow",
            Type = TypeCardEnum.Structure,
            Quality = QualityCardEnum.Epic,
            Elixir=6,
            HitPoints=1000,
            LifeTime=30,
            Damage=26,
            AreaDamage=false,
            InitialLevel=6,
            Target = TargetCardEnum.Ground,
            Radius=3,
            Range=11.5f,
            HitSpeed=0.3f,
            Description="Nice tower you got there. Would be a shame if this X-Bow whittled it down from this side of the Arena...",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/zVQ9Hme1hlj9Dc6e1ORl9xWwglcSrP7ejow5mAhLUJc.png"
        },
        new StructureModel()
        {
            Name="Tombstone",
            Type = TypeCardEnum.Structure,
            Quality = QualityCardEnum.Rare,
            Elixir=3,
            HitPoints=250,
            LifeTime=30,
            Damage=0,
            AreaDamage=false,
            InitialLevel=3,
            Target = TargetCardEnum.Nothing,
            Radius=3,
            Range=0,
            HitSpeed=0,
            Description="Building that periodically spawns Skeletons to fight the enemy... and when destroyed, spawns 4 more Skeletons! Creepy.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/LjSfSbwQfkZuRJY4pVxKspZ-a0iM5KAhU8w-a_N5Z7Y.png"
        },
        new StructureModel()
        {
            Name="Furnace",
            Type = TypeCardEnum.Structure,
            Quality = QualityCardEnum.Rare,
            Elixir=4,
            HitPoints=400,
            LifeTime=28,
            Damage=0,
            AreaDamage=false,
            InitialLevel=3,
            Target = TargetCardEnum.Nothing,
            Radius=3,
            Range=0,
            HitSpeed=0,
            Description="The Furnace spawns one Fire Spirit at a time. It also makes great brick-oven pancakes.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/iqbDiG7yYRIzvCPXdt9zPb3IvMt7F7Gi4wIPnh2x4aI.png"
        },
        new StructureModel()
        {
            Name="Goblin Cage",
            Type = TypeCardEnum.Structure,
            Quality = QualityCardEnum.Rare,
            Elixir=4,
            HitPoints=350,
            LifeTime=20,
            Damage=0,
            AreaDamage=false,
            InitialLevel=3,
            Target = TargetCardEnum.Nothing,
            Radius=3,
            Range=0,
            HitSpeed=0,
            Description="When the Goblin Cage is destroyed, a Goblin Brawler is unleashed into the Arena! Goblin Brawler always skips leg day.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/vD24bBgK4rSq7wx5QEbuqChtPMRFviL_ep76GwQw1yA.png"
        },
        new StructureModel()
        {
            Name="Goblin Drill",
            Type = TypeCardEnum.Structure,
            Quality = QualityCardEnum.Epic,
            Elixir=4,
            HitPoints=900,
            LifeTime=9,
            Damage=0,
            AreaDamage=false,
            InitialLevel=6,
            Target = TargetCardEnum.Nothing,
            Radius=2,
            Range=0,
            HitSpeed=0,
            Description="Building capable of burrowing underground and appearing anywhere in the Arena. Spawns Goblins one at a time until destroyed.",
            ImageUrl="https://api-assets.clashroyale.com/cards/300/eN2TKUYbih-26yBi0xy5LVFOA0zDftgDqxxnVfdIg1o.png"
        },
    };
}
